routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('login'));
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth', 'admin'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/dashboard', 'Admin\DashboardController@index')->name('dashboard');
    Route::resource('drinking', 'DrinkingController');
    Route::patch('drinking/comment/{drinking}', 'DrinkingController@addComment')->name('drinking.addComment');
    Route::get('chart/drink', 'ChartController@generateChart')->name('chart.drink');
    Route::resource('waste', 'WasteController');
    Route::patch('waste/comment/{waste}', 'WasteController@addComment')->name('waste.addComment');
    Route::get('chart/waste', 'ChartController@generateChart')->name('chart.waste');
    Route::resource('clean', 'CleanController');
    Route::patch('clean/comment/{clean}', 'WasteController@addComment')->name('clean.addComment');
    Route::get('chart/clean', 'ChartController@generateChart')->name('chart.clean');
});

Route::group(['middleware' => ['auth', 'operator']], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    
});

app/Clean.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Clean extends Model
{
    protected $fillable = [
        'user_id', 'location', 'kekeruhan', 'warna', 'tds', 'suhu', 'rasa', 'bau', 'ecoli', 'coliform',
        'pH', 'besi', 'flourida', 'kesadahan', 'mangan', 'nitrat', 'nitrit',  'sianida',
        'deterjen', 'pestisida', 'raksa', 'arsen',  'kadmium', 'kromium', 'selenium',
        'seng', 'sulfat', 'timbal', 'benzene', 'organik', 'month', 'created_at', 'updated_at'
    ];

    public function user()
    {
        return $this->belongsTo(\App\User::class);
    }
}

app/Http/Controllers/CleanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Clean;
use Illuminate\Support\Facades\Auth;

class CleanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cleans = Clean::all();
        $testData = $cleans->toArray();

        $cleans->map(function ($clean){
            if($clean['bau'] == 0){
                $clean['bau'] = 'tidak berbau';
            }else{
                $clean['bau'] = 'berbau';
            }

            if($clean['rasa'] == 0){
                $clean['rasa'] = 'tidak berasa';
            }else{
                $clean['rasa'] = 'berasa';
            }
        });

        $rules = array(
            'kekeruhan' => 25,
            'warna' => 50,
            'tds' => 1000,
            'rasa' => 0,
            'bau' => 0,
            'ecoli' => 0,
            'coliform' => 50,
            'pH' => 6.5,
            'besi' => 1,
            'flourida' => 1.5,
            'kesadahan' => 500,
            'mangan' => 0.5,
            'nitrat' => 10,
            'nitrit' => 1,
            'sianida' => 0.1,
            'deterjen' => 0.05,
            'pestisida' => 0.1,
            'raksa' => 0.001,
            'arsen' => 0.05,
            'kadmium' => 0.005,
            'kromium' => 0.05,
            'selenium' => 0.01,
            'seng' => 15,
            'sulfat' => 400,
            'timbal' => 0.05,
            'benzene' => 0.01,
            'organik' => 10,
        );

        $exception = array(
            'id', 'user_id', 'location', 'suhu', 'month', 'comment', 'created_at', 'updated_at'
        );

        $testResult = array();
        foreach ($testData as $preKey => $clean){
            $nComment = 0;
            foreach ($clean as $key => $c){
                if(!in_array($key, $exception)){
                    if($key == 'bau' && $key == 'rasa'){
                        if($clean[$key] == 0){
                            $testResult[$preKey][$key] = 's';
                        }else{
                            $testResult[$preKey][$key] = 'ts';
                            $nComment++;
                        }
                    }elseif($key == 'pH'){
                        if($clean[$key] >= $rules[$key] && $clean[$key] <= $rules[$key]+2){
                            $testResult[$preKey][$key] = 's';
                        }else{
                            $testResult[$preKey][$key] = 'ts';
                            $nComment++;
                        }
                    }else{
                        if($clean[$key] <= $rules[$key]){
                            $testResult[$preKey][$key] = 's';
                        }else{
                            $testResult[$preKey][$key] = 'ts';
                            $nComment++;
                        }
                    }
                }
            }

            if($nComment > 0){
                $testResult[$preKey]['comment'] = true;
            }else{
                $testResult[$preKey]['comment'] = false;
            }
        }

        return view('clean.index', compact('cleans', 'testResult'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('clean.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();
        $input['user_id'] = Auth::user()->id;
        $input['created_at'] = date('Y-m-d H:i:s');

        Clean::create($input);

        return redirect(route('admin.clean.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return null;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $clean = Clean::findOrFail($id);

        return view('clean.edit', compact('clean'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input = $request->all();
        $input['user_id'] = Auth::user()->id;
        $input['updated_at'] = date('Y-m-d H:i:s');

        $clean = Clean::findOrFail($id);
        $clean->update($input);

        return redirect(route('admin.clean.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $clean = Clean::findOrFail($id);
        $clean->delete();

        return redirect(route('admin.clean.index'));
    }

    public function addComment(Request $request, $id){
        $input = request()->only('comment');

        $clean = Clean::findOrFail($id);
        $clean->comment = $input['comment'];
        $clean->save();

        return redirect(route('admin.clean.index'));
    }
}

resources/views/clean/create.blade.php
@extends('layouts.app')

@section('content')
  <div class="header bg-gradient-primary pb-6 pt-5 pt-md-8"></div>
  <div class="container-fluid mt--7">
    <div class="row">
      <div class="col">
        <div class="card shadow">
          <div class="card-header border-0">
            <div class="row align-items-center">
              <div class="col">
                <h3 class="mb-0">Tambah data air bersih</h3>
              </div>
            </div>
          </div>
          <div class="card-body">
            {!! Form::open(['route' => 'admin.clean.store', 'method' => 'post']) !!}

              @include('clean.fields')

            {!! Form::close() !!}
          </div>
        </div>
      </div>
    </div>

    @include('layouts.footer')
      
  </div>
@endsection

resources/views/clean/edit.blade.php
@extends('layouts.app')

@section('content')
  <div class="header bg-gradient-primary pb-6 pt-5 pt-md-8"></div>
  <div class="container-fluid mt--7">
    <div class="row">
      <div class="col">
        <div class="card shadow">
          <div class="card-header border-0">
            <div class="row align-items-center">
              <div class="col">
                <h3 class="mb-0">Edit data</h3>
              </div>
            </div>
          </div>
          <div class="card-body">
            {!! Form::model($clean, ['route' => ['admin.clean.update', $clean->id], 'method' => 'patch']) !!}

              @include('clean.fields')

            {!! Form::close() !!}
          </div>
        </div>
      </div>
    </div>

    @include('layouts.footer')
      
  </div>
@endsection

resources/views/clean/fields.blade.php
<div class="pl-lg-4">
    <div class="row">
        <div class="col-lg-6">
            <div class="form-group">
                {!! Form::select('month', ['Januari' => 'Januari', 'Februari' => 'Februari', 'Maret' => 'Maret', 'April' => 'April', 'Mei' => 'Mei', 'Juni' => 'Juni', 'Juli' => 'Juli', 'Agustus'=>'Agustus', 'September'=>'September', 'Oktober'=>'Oktober', 'November'=>'November', 'Desember'=>'Desember'],null, ['class' => 'form-control form-control-alternative', 'placeholder' => '--Select Month--']) !!}
            </div>
        </div>
        <div class="col-lg-6">
            <div class="form-group">
                {!! Form::text('location', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'Location']) !!}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('kekeruhan', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'Kekeruhan', 'step' => 'any']) !!}
            </div>
        </div>
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('warna', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'Warna', 'step' => 'any']) !!}
            </div>
        </div>
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('tds', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'TDS', 'step' => 'any']) !!}
            </div>
        </div>
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('suhu', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'Suhu', 'step' => 'any']) !!}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::select('rasa', [0 => 'tidak berasa', 1 => 'berasa'], null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'Pilih']) !!}
            </div>
        </div>
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::select('bau', [0 => 'tidak berbau', 1 => 'berbau'], null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'Pilih']) !!}
            </div>
        </div>
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('ecoli', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'E-Coli', 'step' => 'any']) !!}
            </div>
        </div>
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('coliform', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'Coliform', 'step' => 'any']) !!}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('pH', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'pH', 'step' => 'any']) !!}
            </div>
        </div>
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('besi', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'Besi', 'step' => 'any']) !!}
            </div>
        </div>
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('flourida', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'Flourida', 'step' => 'any']) !!}
            </div>
        </div>
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('kesadahan', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'Kesadahan', 'step' => 'any']) !!}
            </div>
        </div>
    </div>
    <div class="row">                
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('mangan', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'Mangan', 'step' => 'any']) !!}
            </div>
        </div>
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('nitrat', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'Nitrat', 'step' => 'any']) !!}
            </div>
        </div>
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('nitrit', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'Nitrit', 'step' => 'any']) !!}
            </div>
        </div>
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('sianida', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'Sianida', 'step' => 'any']) !!}
            </div>
        </div>            
    </div>
    <div class="row">
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('deterjen', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'Deterjen', 'step' => 'any']) !!}
            </div>
        </div>
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('pestisida', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'Pestisida', 'step' => 'any']) !!}
            </div>
        </div>
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('raksa', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'Air Raksa', 'step' => 'any']) !!}
            </div>
        </div>
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('arsen', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'Arsen', 'step' => 'any']) !!}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('kadmium', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'Kadmium', 'step' => 'any']) !!}
            </div>
        </div>
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('kromium', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'Kromium', 'step' => 'any']) !!}
            </div>
        </div>
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('selenium', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'Selenium', 'step' => 'any']) !!}
            </div>
        </div>
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('seng', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'Seng', 'step' => 'any']) !!}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('sulfat', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'Sulfat', 'step' => 'any']) !!}
            </div>
        </div>          
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('timbal', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'Timbal', 'step' => 'any']) !!}
            </div>
        </div>    
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('benzene', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'Benzene', 'step' => 'any']) !!}
            </div>
        </div>    
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('organik', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'Zat Organik', 'step' => 'any']) !!}
            </div>
        </div>        
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a class="btn btn-default" href="{{route('admin.clean.index')}}">Cancel</a>
            </div>
        </div>
    </div>
</div>

resources/views/clean/index.blade.php
@extends('layouts.app')

@section('content')
  <div class="header bg-gradient-primary pb-6 pt-5 pt-md-8"></div>
  <div class="container-fluid mt--7">
    <div class="row">
      <div class="col">
        <div class="card shadow">
          <div class="card-header border-0">
            <div class="row align-items-center">
              <div class="col">
                <h3 class="mb-0">Tabel Air Bersih</h3>
              </div>
              <div class="col text-right">
                <a href="{{route('admin.clean.create')}}" class="btn btn-sm btn-primary">Tambah data</a>
              </div>
            </div>
          </div>
          <div class="table-responsive">
            <table class="table align-items-center table-flush">
              <thead class="thead-light">
                <tr>
                  <th>No</th>
                  <th scope="col">Operator</th>
                  <th scope="col">Location</th>
                  <th scope="col">Month</th>
                  <th scope="col">Comment</th>
                  <th scope="col">Kekeruhan</th>
                  <th scope="col">Warna</th>
                  <th scope="col">TDS</th>
                  <th scope="col">Suhu</th>
                  <th scope="col">Rasa</th>
                  <th scope="col">Bau</th>
                  <th scope="col">E-Coli</th>
                  <th scope="col">Coliform</th>
                  <th scope="col">pH</th>
                  <th scope="col">Besi</th>
                  <th scope="col">Flourida</th>
                  <th scope="col">Kesadahan</th>
                  <th scope="col">Mangan</th>
                  <th scope="col">Nitrat</th>
                  <th scope="col">Nitrit</th>
                  <th scope="col">Sianida</th>
                  <th scope="col">Deterjen</th>
                  <th scope="col">Pestisida</th>
                  <th scope="col">Air Raksa</th>
                  <th scope="col">Arsen</th>
                  <th scope="col">Kadmium</th>
                  <th scope="col">Kromium</th>
                  <th scope="col">Selenium</th>
                  <th scope="col">Seng</th>
                  <th scope="col">Sulfat</th>
                  <th scope="col">Timbal</th>
                  <th scope="col">Benzene</th>
                  <th scope="col">Zat Organik</th>
                  <th scope="col">Created At</th>
                  <th scope="col">Updated At</th>
                  <th class="text-right" scope="col">Action</th>
                </tr>
              </thead>
              <tbody>
                @php
                  $n = 1;
                @endphp
                @foreach ($cleans as $key => $clean)
                  <tr>     
                    <td>{{$n++}}</td>               
                    <td>{{$clean->user->name}}</td>
                    <td>{{$clean->location}}</td>
                    <td>{{$clean->month}}</td>
                    <td>@if($testResult[$key]['comment'] == true)
                        @if($clean->comment == null)
                          <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#inputComment-{{$clean->id}}">Tambah Komentar</button>
                        @else
                          <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#showComment-{{$clean->id}}">Lihat Komentar</button>
                        @endif
                      @else
                        Hasil sesuai standar Permenkes
                      @endif
                    </td>
                    <td @if($testResult[$key]['kekeruhan'] == 'ts') style="color: red" @endif>{{$clean->kekeruhan}}</td>
                    <td @if($testResult[$key]['warna'] == 'ts') style="color: red" @endif>{{$clean->warna}}</td>
                    <td @if($testResult[$key]['tds'] == 'ts') style="color: red" @endif>{{$clean->tds}}</td>
                    <td>{{$clean->suhu}}</td>
                    <td @if($testResult[$key]['rasa'] == 'ts') style="color: red" @endif>{{$clean->rasa}}</td>
                    <td @if($testResult[$key]['bau'] == 'ts') style="color: red" @endif>{{$clean->bau}}</td>
                    <td @if($testResult[$key]['ecoli'] == 'ts') style="color: red" @endif>{{$clean->ecoli}}</td>
                    <td @if($testResult[$key]['coliform'] == 'ts') style="color: red" @endif>{{$clean->coliform}}</td>
                    <td @if($testResult[$key]['pH'] == 'ts') style="color: red" @endif>{{$clean->pH}}</td>
                    <td @if($testResult[$key]['besi'] == 'ts') style="color: red" @endif>{{$clean->besi}}</td>
                    <td @if($testResult[$key]['flourida'] == 'ts') style="color: red" @endif>{{$clean->flourida}}</td>
                    <td @if($testResult[$key]['kesadahan'] == 'ts') style="color: red" @endif>{{$clean->kesadahan}}</td>
                    <td @if($testResult[$key]['mangan'] == 'ts') style="color: red" @endif>{{$clean->mangan}}</td>
                    <td @if($testResult[$key]['nitrat'] == 'ts') style="color: red" @endif>{{$clean->nitrat}}</td>
                    <td @if($testResult[$key]['nitrit'] == 'ts') style="color: red" @endif>{{$clean->nitrit}}</td>
                    <td @if($testResult[$key]['sianida'] == 'ts') style="color: red" @endif>{{$clean->sianida}}</td>
                    <td @if($testResult[$key]['deterjen'] == 'ts') style="color: red" @endif>{{$clean->deterjen}}</td>
                    <td @if($testResult[$key]['pestisida'] == 'ts') style="color: red" @endif>{{$clean->pestisida}}</td>
                    <td @if($testResult[$key]['raksa'] == 'ts') style="color: red" @endif>{{$clean->raksa}}</td>
                    <td @if($testResult[$key]['arsen'] == 'ts') style="color: red" @endif>{{$clean->arsen}}</td>
                    <td @if($testResult[$key]['kadmium'] == 'ts') style="color: red" @endif>{{$clean->kadmium}}</td>
                    <td @if($testResult[$key]['kromium'] == 'ts') style="color: red" @endif>{{$clean->kromium}}</td>
                    <td @if($testResult[$key]['selenium'] == 'ts') style="color: red" @endif>{{$clean->selenium}}</td>
                    <td @if($testResult[$key]['seng'] == 'ts') style="color: red" @endif>{{$clean->seng}}</td>
                    <td @if($testResult[$key]['sulfat'] == 'ts') style="color: red" @endif>{{$clean->sulfat}}</td>
                    <td @if($testResult[$key]['timbal'] == 'ts') style="color: red" @endif>{{$clean->timbal}}</td>
                    <td @if($testResult[$key]['benzene'] == 'ts') style="color: red" @endif>{{$clean->benzene}}</td>
                    <td @if($testResult[$key]['organik'] == 'ts') style="color: red" @endif>{{$clean->organik}}</td>
                    <td>{{$clean->created_at->format('d F Y, H:i')}}</td>
                    <td>{{$clean->updated_at->format('d F Y, H:i')}}</td>
                    <td class="text-right">
                        <div class="dropdown">
                        <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v"></i>
                        </a>
                        {!! Form::open(['route' => ['admin.clean.destroy', $clean->id], 'method' => 'delete']) !!}
                        <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                            <a class="dropdown-item" href="{{route('admin.clean.edit', [$clean->id])}}">Edit</a>
                            {!! Form::button('Delete', ['type' => 'submit', 'class' => 'dropdown-item', 'onclick' => "return confirm('Are you sure to delete this item?')"]) !!}
                        </div>
                        {!! Form::close() !!}
                        </div>
                    </td>
                  </tr>

                  <div id="inputComment-{{$clean->id}}" class="modal fade" role="dialog">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>
                        <div class="modal-body">
                          {!! Form::open(['route' => ['admin.clean.addComment', $clean->id], 'method' => 'post']) !!}
                          @method('PATCH')
                          <div class="pl-lg-4">
                            <div class="row">
                              <div class="col-lg-12">
                                <div class="form-group">
                                  {!! Form::textarea('comment', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'Tulis Komentar']) !!}
                                </div>
                              </div>
                            </div>
                            <div class="row">
                              <div class="col-lg-6">
                                <div class="form-group">
                                  {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                                </div>
                              </div>
                            </div>
                          </div>
                          {!! Form::close() !!}
                        </div>
                      </div>
                    </div>
                  </div>

                  <div id="showComment-{{$clean->id}}" class="modal fade" role="dialog">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>
                        <div class="modal-body">
                          {!! Form::open(['route' => ['admin.clean.addComment', $clean->id], 'method' => 'post']) !!}
                          @method('PATCH')
                          <div class="pl-lg-4">
                            <div class="row">
                              <div class="col-lg-12">
                                <div class="form-group">
                                  {!! Form::textarea('comment', $clean->comment, ['class' => 'form-control form-control-alternative']) !!}
                                </div>
                              </div>
                            </div>
                            <div class="row">
                              <div class="col-lg-6">
                                <div class="form-group">
                                  {!! Form::submit('Update', ['class' => 'btn btn-primary']) !!}
                                </div>
                              </div>
                            </div>
                          </div>
                          {!! Form::close() !!}
                        </div>
                      </div>
                    </div>
                  </div>

                @endforeach
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

    @include('layouts.footer')
      
  </div>
@endsection