routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('login'));
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth', 'admin'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/dashboard', 'Admin\DashboardController@index')->name('dashboard');
    Route::resource('drinking', 'DrinkingController');
    Route::patch('drinking/comment/{drinking}', 'DrinkingController@addComment')->name('drinking.addComment');
    Route::get('chart/drink', 'ChartController@generateChart')->name('chart.drink');
    Route::resource('waste', 'WasteController');
    Route::patch('waste/comment/{waste}', 'WasteController@addComment')->name('waste.addComment');
    Route::get('chart/waste', 'ChartController@generateChart')->name('chart.waste');
    Route::resource('clean', 'CleanController');
    Route::patch('clean/comment/{clean}', 'WasteController@addComment')->name('clean.addComment');
    Route::get('chart/clean', 'ChartController@generateChart')->name('chart.clean');
});

Route::group(['middleware' => ['auth', 'operator']], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    
});

app/Waste.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Waste extends Model
{
    protected $fillable = [
        'user_id', 'location', 'pH', 'bod', 'cod', 'tss', 'oil',
        'amoniak', 'coliform', 'month', 'created_at', 'updated_at'
    ];

    public function user()
    {
        return $this->belongsTo(\App\User::class);
    }
}

app/Http/Controllers/WasteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Waste;
use Illuminate\Support\Facades\Auth;

class WasteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $wastes = Waste::all();
        $testData = $wastes->toArray();

        $rules = array(
            'pH' => 6,
            'bod' => 30,
            'cod' => 100,
            'tss' => 30,
            'oil' => 5,
            'amoniak' => 10,
            'coliform' => 3000,
        );

        $exception = array(
            'id', 'user_id', 'location', 'month', 'comment', 'created_at', 'updated_at'
        );

        $testResult = array();
        foreach ($testData as $preKey => $waste){
            $nComment = 0;
            foreach ($waste as $key => $w){
                if(!in_array($key, $exception)){
                    if($key == 'pH'){
                        if($waste[$key] >= $rules[$key] && $waste[$key] <= $rules[$key]+3){
                            $testResult[$preKey][$key] = 's';
                        }else{
                            $testResult[$preKey][$key] = 'ts';
                            $nComment++;
                        }
                    }else{
                        if($waste[$key] <= $rules[$key]){
                            $testResult[$preKey][$key] = 's';
                        }else{
                            $testResult[$preKey][$key] = 'ts';
                            $nComment++;
                        }
                    }
                }
            }

            if($nComment > 0){
                $testResult[$preKey]['comment'] = true;
            }else{
                $testResult[$preKey]['comment'] = false;
            }
        }

        return view('waste.index', compact('wastes', 'testResult'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('waste.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();
        $input['user_id'] = Auth::user()->id;
        $input['created_at'] = date('Y-m-d H:i:s');

        Waste::create($input);

        return redirect(route('admin.waste.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return null;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $waste = Waste::findOrFail($id);

        return view('waste.edit', compact('waste'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input = $request->all();
        $input['user_id'] = Auth::user()->id;
        $input['updated_at'] = date('Y-m-d H:i:s');

        $waste = Waste::findOrFail($id);
        $waste->update($input);

        return redirect(route('admin.waste.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $waste = Waste::findOrFail($id);
        $waste->delete();

        return redirect(route('admin.waste.index'));
    }

    public function addComment(Request $request, $id){
        $input = request()->only('comment');

        $waste = Waste::findOrFail($id);
        $waste->comment = $input['comment'];
        $waste->save();

        return redirect(route('admin.waste.index'));
    }
}

resources/views/waste/create.blade.php
@extends('layouts.app')

@section('content')
  <div class="header bg-gradient-primary pb-6 pt-5 pt-md-8"></div>
  <div class="container-fluid mt--7">
    <div class="row">
      <div class="col">
        <div class="card shadow">
          <div class="card-header border-0">
            <div class="row align-items-center">
              <div class="col">
                <h3 class="mb-0">Tambah data air limbah</h3>
              </div>
            </div>
          </div>
          <div class="card-body">
            {!! Form::open(['route' => 'admin.waste.store', 'method' => 'post']) !!}

              @include('waste.fields')

            {!! Form::close() !!}
          </div>
        </div>
      </div>
    </div>

    @include('layouts.footer')
      
  </div>
@endsection

resources/views/waste/edit.blade.php
@extends('layouts.app')

@section('content')
  <div class="header bg-gradient-primary pb-6 pt-5 pt-md-8"></div>
  <div class="container-fluid mt--7">
    <div class="row">
      <div class="col">
        <div class="card shadow">
          <div class="card-header border-0">
            <div class="row align-items-center">
              <div class="col">
                <h3 class="mb-0">Edit data</h3>
              </div>
            </div>
          </div>
          <div class="card-body">
            {!! Form::model($waste, ['route' => ['admin.waste.update', $waste->id], 'method' => 'patch']) !!}

              @include('waste.fields')

            {!! Form::close() !!}
          </div>
        </div>
      </div>
    </div>

    @include('layouts.footer')
      
  </div>
@endsection

resources/views/waste/fields.blade.php
<div class="pl-lg-4">
    <div class="row">
        <div class="col-lg-6">
            <div class="form-group">
                {!! Form::select('month', ['Januari' => 'Januari', 'Februari' => 'Februari', 'Maret' => 'Maret', 'April' => 'April', 'Mei' => 'Mei', 'Juni' => 'Juni', 'Juli' => 'Juli', 'Agustus'=>'Agustus', 'September'=>'September', 'Oktober'=>'Oktober', 'November'=>'November', 'Desember'=>'Desember'],null, ['class' => 'form-control form-control-alternative', 'placeholder' => '--Select Month--']) !!}
            </div>
        </div>
        <div class="col-lg-6">
            <div class="form-group">
                {!! Form::text('location', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'Location']) !!}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('pH', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'pH', 'step' => 'any']) !!}
            </div>
        </div>
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('bod', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'BOD', 'step' => 'any']) !!}
            </div>
        </div>
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('cod', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'COD', 'step' => 'any']) !!}
            </div>
        </div>
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('tss', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'TSS', 'step' => 'any']) !!}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('oil', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'Oil', 'step' => 'any']) !!}
            </div>
        </div>
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('amoniak', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'Amoniak', 'step' => 'any']) !!}
            </div>
        </div>
        <div class="col-lg-3">
            <div class="form-group">
                {!! Form::number('coliform', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'Total Coliform', 'step' => 'any']) !!}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a class="btn btn-default" href="{{route('admin.waste.index')}}">Cancel</a>
            </div>
        </div>
    </div>
</div>

resources/views/waste/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="header bg-gradient-primary pb-6 pt-5 pt-md-8"></div>
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col">
                                <h3 class="mb-0">Tabel Air Limbah</h3>
                            </div>
                            <div class="col text-right">
                                <a href="{{route('admin.waste.create')}}" class="btn btn-sm btn-primary">Tambah data</a>
                            </div>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                            <tr>
                                <th>No</th>
                                <th scope="col">Operator</th>
                                <th scope="col">Location</th>
                                <th scope="col">Month</th>
                                <th scope="col">Comment</th>
                                <th scope="col">pH</th>
                                <th scope="col">BOD</th>
                                <th scope="col">COD</th>
                                <th scope="col">TSS</th>
                                <th scope="col">Oil</th>
                                <th scope="col">Amoniak</th>
                                <th scope="col">Total Coliform</th>
                                <th scope="col">Created At</th>
                                <th scope="col">Updated At</th>
                                <th class="text-right" scope="col">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @php
                                $n = 1;
                            @endphp
                            @foreach ($wastes as $key => $waste)
                                <tr>
                                    <td>{{$n++}}</td>
                                    <td>{{$waste->user->name}}</td>
                                    <td>{{$waste->location}}</td>
                                    <td>{{$waste->month}}</td>
                                    <td>@if($testResult[$key]['comment'] == true)
                                            @if($waste->comment == null)
                                                <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#inputComment-{{$waste->id}}">Tambah Komentar</button>
                                            @else
                                                <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#showComment-{{$waste->id}}">Lihat Komentar</button>
                                            @endif
                                        @else
                                            Hasil sesuai standar Permenkes
                                        @endif
                                    </td>
                                    <td @if($testResult[$key]['pH'] == 'ts') style="color: red" @endif>{{$waste->pH}}</td>
                                    <td @if($testResult[$key]['bod'] == 'ts') style="color: red" @endif>{{$waste->bod}}</td>
                                    <td @if($testResult[$key]['cod'] == 'ts') style="color: red" @endif>{{$waste->cod}}</td>
                                    <td @if($testResult[$key]['tss'] == 'ts') style="color: red" @endif>{{$waste->tss}}</td>
                                    <td @if($testResult[$key]['oil'] == 'ts') style="color: red" @endif>{{$waste->oil}}</td>
                                    <td @if($testResult[$key]['amoniak'] == 'ts') style="color: red" @endif>{{$waste->amoniak}}</td>
                                    <td @if($testResult[$key]['coliform'] == 'ts') style="color: red" @endif>{{$waste->coliform}}</td>
                                    <td>{{$waste->created_at->format('d F Y, H:i')}}</td>
                                    <td>{{$waste->updated_at->format('d F Y, H:i')}}</td>
                                    <td class="text-right">
                                        <div class="dropdown">
                                            <a class="btn btn-sm btn-icon-only text-light" href="#" role="button"
                                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <i class="fas fa-ellipsis-v"></i>
                                            </a>
                                            {!! Form::open(['route' => ['admin.waste.destroy', $waste->id], 'method' => 'delete']) !!}
                                            <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                <a class="dropdown-item"
                                                   href="{{route('admin.waste.edit', [$waste->id])}}">Edit</a>
                                                {!! Form::button('Delete', ['type' => 'submit', 'class' => 'dropdown-item', 'onclick' => "return confirm('Are you sure to delete this item?')"]) !!}
                                            </div>
                                            {!! Form::close() !!}
                                        </div>
                                    </td>
                                </tr>

                                <div id="inputComment-{{$waste->id}}" class="modal fade" role="dialog">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                            </div>
                                            <div class="modal-body">
                                                {!! Form::open(['route' => ['admin.waste.addComment', $waste->id], 'method' => 'post']) !!}
                                                @method('PATCH')
                                                <div class="pl-lg-4">
                                                    <div class="row">
                                                        <div class="col-lg-12">
                                                            <div class="form-group">
                                                                {!! Form::textarea('comment', null, ['class' => 'form-control form-control-alternative', 'placeholder' => 'Tulis Komentar']) !!}
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col-lg-6">
                                                            <div class="form-group">
                                                                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                {!! Form::close() !!}
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div id="showComment-{{$waste->id}}" class="modal fade" role="dialog">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                            </div>
                                            <div class="modal-body">
                                                {!! Form::open(['route' => ['admin.waste.addComment', $waste->id], 'method' => 'post']) !!}
                                                @method('PATCH')
                                                <div class="pl-lg-4">
                                                    <div class="row">
                                                        <div class="col-lg-12">
                                                            <div class="form-group">
                                                                {!! Form::textarea('comment', $waste->comment, ['class' => 'form-control form-control-alternative']) !!}
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col-lg-6">
                                                            <div class="form-group">
                                                                {!! Form::submit('Update', ['class' => 'btn btn-primary']) !!}
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                {!! Form::close() !!}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        @include('layouts.footer')

    </div>
@endsection