routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('login'));
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth', 'admin'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/dashboard', 'Admin\DashboardController@index')->name('dashboard');
    Route::resource('drinking', 'DrinkingController');
    Route::patch('drinking/comment/{drinking}', 'DrinkingController@addComment')->name('drinking.addComment');
    Route::get('chart/drink', 'ChartController@generateChart')->name('chart.drink');
    Route::resource('waste', 'WasteController');
    Route::patch('waste/comment/{waste}', 'WasteController@addComment')->name('waste.addComment');
    Route::get('chart/waste', 'ChartController@generateChart')->name('chart.waste');
    Route::resource('clean', 'CleanController');
    Route::patch('clean/comment/{clean}', 'WasteController@addComment')->name('clean.addComment');
    Route::get('chart/clean', 'ChartController@generateChart')->name('chart.clean');
});

Route::group(['middleware' => ['auth', 'operator']], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    
});

resources/views/admin/dashboard.blade.php
@extends('layouts.app')

@section('content')
    <div class="header bg-gradient-primary pb-8 pt-5 pt-md-8">
        <div class="container-fluid">
          <div class="header-body">
            <!-- Card stats -->
            <div class="row">
              <div class="col-xl-4 col-lg-6">
                <div class="card card-stats mb-4 mb-xl-0">
                  <div class="card-body">
                    <div class="row">
                      <div class="col">
                        <h5 class="card-title text-uppercase text-muted mb-0">Air Minum</h5>
                        <span class="h2 font-weight-bold mb-0">{{$drinking}}</span>
                      </div>
                      <div class="col-auto">
                        <a href="{{route('admin.drinking.create')}}">
                          <div class="icon icon-shape bg-danger text-white rounded-circle shadow">
                            <i class="fas fa-plus"></i>
                          </div>
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xl-4 col-lg-6">
                <div class="card card-stats mb-4 mb-xl-0">
                  <div class="card-body">
                    <div class="row">
                      <div class="col">
                        <h5 class="card-title text-uppercase text-muted mb-0">Air Limbah</h5>
                        <span class="h2 font-weight-bold mb-0">{{$waste}}</span>
                      </div>
                      <div class="col-auto">
                        <a href="{{route('admin.waste.create')}}">
                          <div class="icon icon-shape bg-danger text-white rounded-circle shadow">
                              <i class="fas fa-plus"></i>
                          </div>
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xl-4 col-lg-6">
                <div class="card card-stats mb-4 mb-xl-0">
                  <div class="card-body">
                    <div class="row">
                      <div class="col">
                        <h5 class="card-title text-uppercase text-muted mb-0">Air Bersih</h5>
                        <span class="h2 font-weight-bold mb-0">{{$clean}}</span>
                      </div>
                      <div class="col-auto">
                        <a href="{{route('admin.clean.create')}}">
                          <div class="icon icon-shape bg-danger text-white rounded-circle shadow">
                              <i class="fas fa-plus"></i>
                          </div>
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
@endsection