routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('login'));
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth', 'admin'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/dashboard', 'Admin\DashboardController@index')->name('dashboard');
    Route::resource('drinking', 'DrinkingController');
    Route::patch('drinking/comment/{drinking}', 'DrinkingController@addComment')->name('drinking.addComment');
    Route::get('chart/drink', 'ChartController@generateChart')->name('chart.drink');
    Route::resource('waste', 'WasteController');
    Route::patch('waste/comment/{waste}', 'WasteController@addComment')->name('waste.addComment');
    Route::get('chart/waste', 'ChartController@generateChart')->name('chart.waste');
    Route::resource('clean', 'CleanController');
    Route::patch('clean/comment/{clean}', 'WasteController@addComment')->name('clean.addComment');
    Route::get('chart/clean', 'ChartController@generateChart')->name('chart.clean');
});

Route::group(['middleware' => ['auth', 'operator']], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="water quality control">
    <meta name="author" content="vedo alfarizi">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <link href="{{asset('img/favicon.png')}}" rel="icon" type="image/png">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <link href="{{asset('css/nucleo.css')}}" rel="stylesheet">
    <link href="{{asset('css/font-awesome.min.css')}}" rel="stylesheet">
    <link type="text/css" href="{{asset('css/argon.min.css')}}" rel="stylesheet">
    <link type="text/css" href="{{asset('css/style.css')}}" rel="stylesheet">

    <script src="{{asset('js/jquery.min.js')}}"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.min.js"></script>
    <script src="{{asset('js/chart.js')}}"></script>

</head>
<body>
    <nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
        <div class="container-fluid">
            <!-- Toggler -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!-- Brand -->
            <a class="navbar-brand pt-0" href="{{url('/')}}">
                <img src="{{asset('img/favicon.png')}}" class="navbar-brand-img" alt="...">
            </a>

            <!-- Collapse -->
            <div class="collapse navbar-collapse" id="sidenav-collapse-main">
                <!-- Collapse header -->
                <div class="navbar-collapse-header d-md-none">
                    <div class="row">
                        <div class="col-6 collapse-brand">
                            <a href="./index.html">
                                <img src="{{asset('img/favicon.png')}}">
                            </a>
                        </div>
                        <div class="col-6 collapse-close">
                            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                                <span></span>
                                <span></span>
                            </button>
                        </div>
                    </div>
                </div>
                
                @include('layouts.menu')
            </div>
        </div>
        </nav>

        <div class="main-content">
            @include('layouts.nav')
            @yield('content')
        </div>

    <script src="{{asset('js/bootstrap-datepicker.min.js')}}"></script>
    <script src="{{asset('js/bootstrap.bundle.min.js')}}"></script>
    <script src="{{asset('js/argon.min.js')}}"></script>

</body>
</html>

resources/views/layouts/footer.blade.php
<footer class="footer">
    <div class="row align-items-center justify-content-xl-between">
        <div class="col-xl-6">
        <div class="copyright text-center text-xl-left text-muted">
            &copy; 2018 Template Design by<a href="https://www.creative-tim.com" class="font-weight-bold ml-1" target="_blank">Creative Tim</a>
        </div>
        </div>
        <div class="col-xl-6">
            <div class="copyright text-center text-xl-right text-muted">
                Developed by<a href="https://www.linkedin.com/in/vedo-alfarizi-56a04b145/" class="font-weight-bold ml-1" target="_blank">Vedo Alfarizi</a>
            </div>
        </div>
    </div>
</footer>

resources/views/layouts/menu.blade.php
@if(Auth::user()->role == 0)
<ul class="navbar-nav">   
    <li class="nav-item {{ Request::is('admin/dashboard*') ? 'active' : '' }}">
        <a class="nav-link" href="{{route('admin.dashboard')}}">
            <i class="ni ni-tv-2 text-primary"></i> Dashboard
        </a>
    </li> 
    <li class="nav-item {{ Request::is('admin/drinking*') ? 'active' : '' }}">
        <a class="nav-link" href="{{route('admin.drinking.index')}}">
            <i class="ni ni-tv-2 text-primary"></i> Air Minum
        </a>
    </li>
    {!! Form::open(['route' => 'admin.chart.drink', 'method' => 'GET']) !!}
    <li class="nav-item {{ Request::is('admin/chart/drink*') ? 'active' : '' }}">
        <input type="hidden" name="year" value="{{date('Y')}}">
        <input type="hidden" name="type" value="drink">
        <button class="nav-link btn btn-white btn-block" type="submit"><i class='ni ni-tv-2 text-primary'></i> Grafik Air Minum</button>
    </li>
    {!! Form::close() !!}
    <li class="nav-item {{ Request::is('admin/waste*') ? 'active' : '' }}">
        <a class="nav-link" href="{{route('admin.waste.index')}}">
            <i class="ni ni-tv-2 text-primary"></i> Air Limbah
        </a>
    </li>
    {!! Form::open(['route' => 'admin.chart.waste', 'method' => 'GET']) !!}
    <li class="nav-item {{ Request::is('admin/chart/waste*') ? 'active' : '' }}">
        <input type="hidden" name="year" value="{{date('Y')}}">
        <input type="hidden" name="type" value="waste">
        <button class="nav-link btn btn-white btn-block" type="submit"><i class='ni ni-tv-2 text-primary'></i> Grafik Air Limbah</button>
    </li>
    {!! Form::close() !!}
    <li class="nav-item {{ Request::is('admin/clean*') ? 'active' : '' }}">
        <a class="nav-link" href="{{route('admin.clean.index')}}">
            <i class="ni ni-tv-2 text-primary"></i> Air Bersih
        </a>
    </li>
    {!! Form::open(['route' => 'admin.chart.clean', 'method' => 'GET']) !!}
    <li class="nav-item {{ Request::is('admin/chart/clean*') ? 'active' : '' }}">
        <input type="hidden" name="year" value="{{date('Y')}}">
        <input type="hidden" name="type" value="clean">
        <button class="nav-link btn btn-white btn-block" type="submit"><i class='ni ni-tv-2 text-primary'></i> Grafik Air Bersih</button>
    </li>
    {!! Form::close() !!}
</ul>
@elseif(Auth::user()->role == 1)
<ul class="navbar-nav">   
    <li class="nav-item {{ Request::is('dashboard*') ? 'active' : '' }}">
        <a class="nav-link" href="{{route('dashboard')}}">
            <i class="ni ni-tv-2 text-primary"></i> Dashboard
        </a>
    </li> 
</ul>
@endif
<ul class="navbar-nav">    
    <li class="nav-item">
        <a class="nav-link" href="{{ route('logout') }}" onclick="event.preventDefault();
        document.getElementById('logout-form').submit();">
            <i class="ni ni-user-run text-pink"></i> Logout
        </a>
        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            @csrf
        </form>
    </li>
</ul>

resources/views/layouts/nav.blade.php
<nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
        <div class="container-fluid">
          <!-- Brand -->
          <a class="h4 mb-0 text-white text-uppercase d-none d-lg-inline-block" href="#">Water Quality Control</a>
          
          <!-- User -->
          <ul class="navbar-nav align-items-center d-none d-md-flex">
            <li class="nav-item dropdown">
              <a class="nav-link pr-0">
                <div class="media align-items-center">
                  <div class="media-body ml-2 d-none d-lg-block">
                    <span class="mb-0 text-sm font-weight-bold">{{Auth::user()->name}} | @if(Auth::user()->role == 0) Admin @else Operator @endif</span>
                  </div>
                </div>
              </a>
            </li>
          </ul>
        </div>
      </nav>